export const headerImagesItem = [
  {image:"p1.png"},
  {image:"p2.png"},
  {image:"p3.png"},
  {image:"p4.png"},
  {image:"p5.png"},
  {image:"p6.png"},
  {image:"p7.png"},
  {image:"p8.png"},
  {image:"p9.png"},
  {image:"p10.png"},
  {image:"p11.png"},
  {image:"p12.png"},
  {image:"p13.png"},
  {image:"p14.png"},
  {image:"p15.png"},
  {image:"p16.png"},
  {image:"p17.png"},
  {image:"p18.png"},
  {image:"p19.png"},
  {image:"p20.png"},
  {image:"p21.png"},
  {image:"p22.png"},
  {image:"p23.png"},
  {image:"p24.png"},
  {image:"p25.png"},
  {image:"p26.png"},
  {image:"p27.png"},
  {image:"p28.png"},
  {image:"p29.png"},
  {image:"p30.png"},
  {image:"p31.png"},
  {image:"p32.png"},
  {image:"p33.png"},
  {image:"p34.png"},
  {image:"p35.png"},
  {image:"p36.png"},
  {image:"p37.png"},
  {image:"p38.png"},
  {image:"p39.png"},
  {image:"p40.png"},
  {image:"p41.png"},
  {image:"p42.png"},
  {image:"p43.png"},
  {image:"p44.png"},
  {image:"p45.png"},
  {image:"p46.png"},
  {image:"p47.png"},
  {image:"p48.png"},
  {image:"p49.png"},
]

export const workitems = [
  {
    id:1,
    title:"幫畫寫實",
    message:"幫畫寫實 白雪公主" ,
    images:[
      "sd/p01.png",
      "sd/p02.png",
      "sd/p03.png",
      "sd/p04.png",
    ]
  },
  {
    id:2,
    title:"幫畫概念", 
    message:"幫畫概念 角色設計,穿著鎧甲的女孩,Cyberpunk" ,
    images:[
      "mj/p01.png",
      "mj/p02.png",
      "mj/p03.png",
      "mj/p04.png",
    ]
  },
  {
    id:3,
    title:"幫畫漫畫", 
    message:"幫畫漫畫 放學的快樂高中生" ,
    images:[
      "nv/p01.png",
      "nv/p02.png",
      "nv/p03.png",
      "nv/p04.png",
    ]
  },
  {
    id:4,
    title:"幫畫科幻", 
    message:"幫畫科幻 幻想中的紫色怪物" ,
    images:[
      "sc/p01.png",
      "sc/p02.png",
      "sc/p03.png",
      "sc/p04.png",
    ]
  }
]

export const workitems2 = [
  {
    id:1,
    title:"參考寫實", 
    message:"參考寫實 未來消防員" ,
    image:'m01.png',
    images:[
      "rsd/p01.png",
      "rsd/p02.png",
      "rsd/p03.png",
    ]
  },
  {
    id:2,
    title:"參考概念", 
    message:"參考概念 未來消防員" ,
    image:'m01.png',
    images:[
      "rmj/p01.png",
      "rmj/p02.png",
      "rmj/p03.png",
    ]
  },
  {
    id:3,
    title:"參考漫畫", 
    message:"參考漫畫 白雪公主" ,
    image:'m02.png',
    images:[
      "rnv/p01.png",
      "rnv/p02.png",
      "rnv/p03.png",
    ]
  },
  {
    id:4,
    title:"參考科幻", 
    message:"參考科幻 白雪公主" ,
    image:'m02.png',
    images:[
      "rsc/p01.png",
      "rsc/p02.png",
      "rsc/p03.png",
    ]
  }
]