name: Build and Deploy

on:
  workflow_call:
    inputs:
      env_input:
        type: string
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloud Run
    environment: ${{ inputs.env_input }}
    env:
      CI: false
      REACT_APP_LIFF_LOGIN_ID: ${{ secrets.LIFF_LOGIN_ID }}
      REACT_APP_MOONSHOT_LINELOGIN_APIKEY: ${{secrets.MOONSHOT_LINELOGIN_APIKEY}}
      REACT_APP_MOONSHOT_API_URL: ${{ secrets.MOONSHOT_API_URL }}
      REACT_APP_LIFF_PROMPT_ID: ${{secrets.LIFF_PROMPT_ID}}
      REACT_APP_LIFF_GERNERATOR_ID: ${{secrets.LIFF_GERNERATOR_ID}}
      REACT_APP_FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      REACT_APP_FIREBASE_DOMAIN: ${{ secrets.FIREBASE_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_SENDER_ID: ${{ secrets.FIREBASE_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      REACT_APP_FULLBODY_TOKEN_KEY: ${{ secrets.FULLBODY_TOKEN_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install and build (Web)
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Install (Functions)
        working-directory: functions
        run: |
          yarn install --frozen-lockfile
      - name: Copy index.html
        run: |
          mkdir -p functions/source
          cp build/index.html functions/source/index.html
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy -P ${{ secrets.FIREBASE_PROJECT }} --only hosting,functions:host
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
